###
# Site variables
###

development: app/

server: server/

destination: public/

destination_assets: public/assets/

deploy: ../dz-heroku/

deploy_site: ../dz-heroku/public

deploy_assets: ../dz-heroku/public/assets

deploy_server: ../dz-heroku/server

deploy_server_assets: ../dz-heroku/
